name: PR Auto-Labeler Reusable Workflow

# Auto labeled PR based on HEAD branch name.

# Usage example:
# on:
#   pull_request:
#     types:
#       - opened

on:
  workflow_call:

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: PR Auto Labeler
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-labeler-config.yml
          disable-autolabeler: false
          disable-releaser: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}